#!/usr/bin/env bash
# Drive betl_bench across (shape × mode) combinations and print a
# markdown table summary. Designed to be invoked by `make bench`,
# which substitutes the absolute path to the bench binary as $1.
#
# Each (shape, mode) runs in its own subprocess so async_stream's
# env-cached parallel toggle picks up the right setting fresh.

set -euo pipefail

bin="${1:-./build/bench/betl_bench}"
if [[ ! -x "$bin" ]]; then
    echo "betl_bench binary not found at: $bin" >&2
    exit 1
fi

# Default sweep parameters; override via env. ROWS_LARGE is the I/O-
# shape file size proxy — keep it large enough to swamp warmup noise.
# ROWS_PC defaults smaller because dotnet.pipelinecomponent has higher
# per-row overhead (C↔C# crossings + AOT path) and 100k rows is enough
# to swamp µs-level timing noise without taking a full minute per iter.
ITERS="${BETL_BENCH_ITERS:-5}"
ROWS_SMALL="${BETL_BENCH_ROWS:-1000000}"
ROWS_LARGE="${BETL_BENCH_CSV_ROWS:-1000000}"
ROWS_PC="${BETL_BENCH_PC_ROWS:-100000}"

# Provider library / deps load paths — providers/* sit next to bench/
# in the build tree; deps/lib carries libpq / libyaml / etc.
script_dir="$(cd "$(dirname "$0")" && pwd)"
deps_lib="$script_dir/../deps/lib"
export LD_LIBRARY_PATH="$deps_lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# Each shape: name + rows + label. The csv-rt shape uses ROWS_LARGE
# (controls input file size); the rest use ROWS_SMALL.
declare -a SHAPES=(
    "filter-count|$ROWS_SMALL|gen → filter(true) → count"
    "map-arith|$ROWS_SMALL|gen → ssisexpr arithmetic → count"
    "sort|$ROWS_SMALL|gen → sort desc → count (materializes)"
    "chain|$ROWS_SMALL|gen → 4× ssisexpr map → count"
    "csv-rt|$ROWS_LARGE|csv.read → ssisexpr map → csv.write"
    "pc-passthrough-1col|$ROWS_PC|dotnet.pipelinecomponent 1-col passthrough"
    "pc-passthrough-10col|$ROWS_PC|dotnet.pipelinecomponent 10-col passthrough"
    "pc-error-route|$ROWS_PC|dotnet.pipelinecomponent error_output (10% tagged)"
    "pc-decimal|$ROWS_PC|dotnet.pipelinecomponent 5 decimal cells/row"
    "pc-async-aggregate|$ROWS_PC|dotnet.pipelinecomponent async N → 1 summary"
    "pc-vs-lua-script|$ROWS_PC|lua.script 1-col passthrough (baseline for pc)"
)

# Each mode: env settings + label.
declare -a MODES=(
    "serial|BETL_PARALLEL=off"
    "par1|BETL_PARALLEL=on BETL_PARALLEL_DEPTH=1"
    "par4|BETL_PARALLEL=on BETL_PARALLEL_DEPTH=4"
)

results_file="$(mktemp)"
trap 'rm -f "$results_file"' EXIT

for shape_entry in "${SHAPES[@]}"; do
    IFS='|' read -r shape rows description <<<"$shape_entry"
    echo "# $shape ($rows rows): $description" >&2
    for mode_entry in "${MODES[@]}"; do
        IFS='|' read -r mode envs <<<"$mode_entry"
        # Build the env-prefix string and run in a subshell so the env
        # is fresh for each invocation (async_stream caches its flags).
        # BETL_DOTNET_ROOT propagated through env -i so the dotnet shapes
        # can find the SDK; benign for non-dotnet shapes.
        set +e
        out=$(env -i HOME="$HOME" PATH="$PATH" \
              LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
              BETL_DOTNET_ROOT="${BETL_DOTNET_ROOT:-}" \
              $envs "$bin" "$shape" "$ITERS" --rows "$rows" --mode "$mode")
        rc=$?
        set -e
        if [[ $rc -eq 77 ]]; then
            echo "  $mode: SKIPPED" >&2
            continue
        fi
        if [[ $rc -ne 0 ]]; then
            echo "  $mode: FAILED" >&2
            continue
        fi
        echo "  $mode: $out" >&2
        echo "$out" >> "$results_file"
    done
done

# Render markdown. Group rows by shape, columns by mode.
# Default output sits in the project's docs/ next to other reference
# docs, anchored to the script's own location so cwd doesn't matter.
project_root="$(cd "$script_dir/.." && pwd)"
out_md="${BETL_BENCH_OUT:-$project_root/docs/BENCHMARKS.md}"
mkdir -p "$(dirname "$out_md")"
{
    echo "# betl benchmarks"
    echo
    echo "Generated by \`bench/run.sh\`. Each cell is wall-clock"
    echo "milliseconds (min of $ITERS iterations after one warm-up run)."
    echo "Speedup column compares the best parallel mode to serial."
    echo
    echo "Host: \`$(uname -srm 2>/dev/null || echo unknown)\` —"
    echo "$(nproc 2>/dev/null || echo '?') logical CPUs."
    echo
    echo "## How to read these numbers"
    echo
    echo "betl's parallelism is **pipeline parallelism**: every"
    echo "producer-consumer edge between adjacent steps gets a"
    echo "background thread + ring buffer (depth set by"
    echo "\`BETL_PARALLEL_DEPTH\`). Steps in a chain run concurrently"
    echo "on different CPUs."
    echo
    echo "What that implies:"
    echo
    echo "- **Long chains of CPU-bound steps** speed up the most."
    echo "  Each stage's work overlaps with its neighbours' work."
    echo "  See \`chain\` below."
    echo "- **Trivial pipelines** are flat or slightly slower."
    echo "  The ring-buffer handoff adds ~µs of overhead per batch."
    echo "  See \`filter-count\` and \`map-arith\` below."
    echo "- **Materialising steps** (sort, aggregate) can't overlap"
    echo "  with downstream work — the whole input has to land first."
    echo "  See \`sort\` below."
    echo "- **I/O-bound pipelines** benefit modestly; the I/O step's"
    echo "  syscall time overlaps with the CPU step's compute."
    echo "  See \`csv-rt\` below."
    echo
    echo "### dotnet.pipelinecomponent shapes (\`pc-*\`)"
    echo
    echo "The \`pc-*\` shapes exercise the NativeAOT-compiled SSIS"
    echo "PipelineComponent path. Each first-run incurs a one-time AOT"
    echo "publish (a few seconds for a trivial component); subsequent"
    echo "runs hit the per-source-hash compile cache and are near-zero"
    echo "warmup. The harness's pre-timing warmup absorbs that compile,"
    echo "so the reported numbers are steady-state per-row throughput."
    echo
    echo "Throughput notes:"
    echo
    echo "- **Single-cell I/O is cheap.** \`pc-passthrough-1col\` and"
    echo "  \`pc-async-aggregate\` show >10M rows/s — the C↔C# crossings"
    echo "  per cell aren't the bottleneck for narrow rows."
    echo "- **Throughput scales linearly with column count.** 10-col"
    echo "  passthrough is ~3× slower than 1-col — each Get/Set is its"
    echo "  own function-pointer call."
    echo "- **Error routing adds negligible overhead** when a small"
    echo "  fraction of rows are tagged (\`pc-error-route\` vs"
    echo "  \`pc-passthrough-1col\`)."
    echo "- **decimal128 is ~5× slower than int64**, with the bulk of"
    echo "  the cost now in the per-cell \`new byte[16]\` heap allocation"
    echo "  on the C# side rather than the 128-bit arithmetic itself"
    echo "  (the original BigInteger-based path was ~10× slower; the"
    echo "  switch to System.Int128 / UInt128 + power-of-10 lookup more"
    echo "  than doubled throughput). Further speedup would need a"
    echo "  staging refactor to use stackalloc Span<byte> instead of"
    echo "  heap-allocated byte[]."
    echo "- **Async aggregator is fastest.** Only one output row total,"
    echo "  no per-row Set in the user code."
    echo "- **Parallel mode is a wash** for these shapes — the dotnet"
    echo "  component is the single hot stage, with little for the"
    echo "  pipeline-parallel executor to overlap."
    echo "- **Comparison vs lua.script:** \`pc-vs-lua-script\` runs the"
    echo "  same 1-col passthrough through Lua's VM. dotnet (NativeAOT)"
    echo "  is roughly 2.5–3× faster than Lua here. The trade-off is"
    echo "  startup: lua.script has no AOT compile."
    echo
    echo "Reproduce: \`make bench\` (or \`bench/run.sh\` directly)."
    echo "Tunables: \`BETL_BENCH_ITERS\`, \`BETL_BENCH_ROWS\`,"
    echo "\`BETL_BENCH_CSV_ROWS\`, \`BETL_BENCH_PC_ROWS\`."
    echo
    for shape_entry in "${SHAPES[@]}"; do
        IFS='|' read -r shape rows description <<<"$shape_entry"
        echo "## \`$shape\` — $description"
        echo
        echo "Rows: $rows"
        echo
        # Pull values for this shape.
        serial_ms=""
        par1_ms=""
        par4_ms=""
        for mode_entry in "${MODES[@]}"; do
            IFS='|' read -r mode _envs <<<"$mode_entry"
            line=$(grep "^$shape,$mode," "$results_file" || true)
            if [[ -z "$line" ]]; then continue; fi
            # CSV: shape,mode,iters,rows,wall_min,wall_p50,wall_max,wall_mean,user,sys,maxrss,rps
            wmin=$(echo "$line"  | awk -F, '{print $5}')
            wp50=$(echo "$line"  | awk -F, '{print $6}')
            wmax=$(echo "$line"  | awk -F, '{print $7}')
            rps=$(echo "$line"   | awk -F, '{print $12}')
            maxrss=$(echo "$line" | awk -F, '{print $11}')
            case "$mode" in
                serial) serial_ms="$wmin" ;;
                par1)   par1_ms="$wmin" ;;
                par4)   par4_ms="$wmin" ;;
            esac
            printf -- "- **%s**: min=%s ms · p50=%s ms · max=%s ms · %s rows/s · maxrss=%s KB\n" \
                "$mode" "$wmin" "$wp50" "$wmax" "$rps" "$maxrss"
        done
        if [[ -n "$serial_ms" && -n "$par4_ms" ]]; then
            speedup=$(awk -v s="$serial_ms" -v p="$par4_ms" 'BEGIN{ if (p>0) printf "%.2fx", s/p; else print "—" }')
            echo
            echo "**Speedup (serial → par4): $speedup**"
        fi
        echo
    done
} > "$out_md"

echo
echo "Wrote $out_md"
