/* Base class for user-defined dotnet.script async transforms.
 *
 * User convention: declare a public class named `UserScript` that
 * extends BetlScript and overrides OnRow / OnEof. The plugin
 * generates strongly-typed InputRow / OutputRow classes from the
 * pipeline's input and declared output_schema, so OnRow receives an
 * InputRow with typed properties named exactly like the input
 * columns; Emit takes an OutputRow built from output_schema.
 *
 *   public class UserScript : Betl.BetlScript {
 *       readonly List<double> window = new();
 *       public override void OnRow(InputRow row) {
 *           window.Add(row.value ?? 0.0);
 *           if (window.Count > 10) window.RemoveAt(0);
 *           if (window.Count == 10) {
 *               Emit(new OutputRow { id = row.id, smoothed = window.Average() });
 *           }
 *       }
 *       public override void OnEof() {
 *           // optional final flush
 *       }
 *   }
 *
 * Emit may be called zero or more times from OnRow / OnEof. The
 * runtime accumulates rows and flushes them to the downstream
 * Arrow stream at end of each input batch (so a fan-in script that
 * only emits at OnEof gets a single output batch at the end). */

namespace Betl;

public abstract class BetlScript
{
    public abstract void OnRow(InputRow row);
    public virtual  void OnEof() { }

    /* Generated by the plugin; the static `Emit` method actually
     * marshals the row through the host. The instance Emit() here is
     * just sugar so user code reads naturally. */
    protected void Emit(OutputRow row) => Dispatch.EmitRow(row);
}
