/* DtsxPackage → betl YAML. Holds the high-level walk; per-component
 * mappers live in Mappers/. */

using System;
using System.Collections.Generic;
using System.Linq;

namespace Betl.Dtsx2Yaml;

public static class Converter
{
    public static string PackageToYaml(DtsxPackage pkg, bool verbose = false)
    {
        var w = new YamlWriter();

        w.Line("# Generated by betl-dtsx2yaml from DTSX source.");
        w.Line("# Manual edits expected for: connection DSNs (provider-string");
        w.Line("# translation is approximate), upsert key columns (SSIS OLEDB");
        w.Line("# Destination has no key concept), and any TODO markers below.");
        w.Line();
        w.Line("betl: 1");
        w.Line("name: " + YamlWriter.Id(pkg.Name));

        EmitConnections(w, pkg);
        EmitParameters(w, pkg);
        EmitPipeline(w, pkg, verbose);

        return w.ToString();
    }

    static void EmitConnections(YamlWriter w, DtsxPackage pkg)
    {
        if (pkg.Connections.Count == 0) return;
        w.Line();
        w.Line("connections:");
        w.Indent(2);
        foreach (var c in pkg.Connections)
        {
            switch (c.CreationName)
            {
                case "OLEDB":
                case "ADO.NET":
                    Mappers.OledbConnection.Emit(w, c);
                    break;
                case "FLATFILE":
                    /* Flat file "connections" in SSIS hold the file path;
                     * we don't emit a betl connection for them — the path
                     * is inlined when the source/destination references it.
                     * Drop a comment so a verbose pass can see we noticed. */
                    w.Comment($"flat-file connection '{c.Name}' → inlined into csv.read / csv.write");
                    break;
                default:
                    w.Comment($"TODO: connection '{c.Name}' has unsupported "
                            + $"CreationName '{c.CreationName}' — manual migration required");
                    break;
            }
        }
        w.Indent(-2);
    }

    static void EmitParameters(YamlWriter w, DtsxPackage pkg)
    {
        if (pkg.Variables.Count == 0) return;
        var user = pkg.Variables.Where(v => v.Namespace == "User").ToList();
        if (user.Count == 0) return;
        w.Line();
        w.Line("parameters:");
        w.Indent(2);
        foreach (var v in user)
        {
            w.Line(YamlWriter.Id(v.Name) + ":");
            w.Indent(2);
            w.Line("type: " + MapVariableType(v.DataType));
            if (!string.IsNullOrEmpty(v.ValueRaw))
                w.Line("default: " + YamlWriter.Quote(v.ValueRaw));
            w.Indent(-2);
        }
        w.Indent(-2);
    }

    static string MapVariableType(int dtsType)
    {
        /* https://learn.microsoft.com/en-us/dotnet/api/system.typecode
         * SSIS' DataType attribute on Variable values uses .NET TypeCode
         * enum values. */
        return dtsType switch
        {
            3  => "int",        /* Int32 */
            6  => "int",        /* UInt32 */
            7  => "decimal",    /* Single — closest betl analogue */
            13 => "decimal",    /* Double */
            16 => "date",       /* DateTime */
            18 => "string",     /* String */
            _  => "string",
        };
    }

    static void EmitPipeline(YamlWriter w, DtsxPackage pkg, bool verbose)
    {
        if (pkg.Executables.Count == 0) return;
        w.Line();
        w.Line("pipeline:");
        w.Indent(2);
        foreach (var exe in pkg.Executables)
        {
            switch (exe.Kind)
            {
                case "Microsoft.Pipeline":
                    EmitDataflow(w, pkg, exe, verbose);
                    break;
                case "Microsoft.ExecuteSQLTask":
                    Mappers.ExecuteSqlTask.Emit(w, pkg, exe);
                    break;
                case "Microsoft.ScriptTask":
                    Mappers.ScriptTask.Emit(w, pkg, exe);
                    break;
                default:
                    w.Line($"- id: {YamlWriter.Id(exe.Name)}");
                    w.Indent(2);
                    w.Comment($"TODO: executable type '{exe.Kind}' not yet supported "
                            + "— manual migration required");
                    w.Indent(-2);
                    break;
            }
        }
        w.Indent(-2);
    }

    static void EmitDataflow(YamlWriter w, DtsxPackage pkg, DtsxExecutable exe, bool verbose)
    {
        w.Line($"- id: {YamlWriter.Id(exe.Name)}");
        w.Indent(2);
        w.Line("type: dataflow");
        w.Line("steps:");
        w.Indent(2);

        /* Component-id map: refId → betl `id` (lower_snake_case from
         * the SSIS name) and refId → class for from-ref formatting
         * decisions. */
        var refToId    = exe.Components.ToDictionary(c => c.RefId,
                                                     c => YamlWriter.Id(c.Name));
        var refToClass = exe.Components.ToDictionary(c => c.RefId, c => c.ClassId);

        /* Predecessor map keyed by downstream component ref. Each
         * predecessor entry carries enough to format a port-aware
         * `from:` ref and to disambiguate multi-input downstreams (e.g.
         * Merge Join's Left vs Right input). */
        var predecessors = new Dictionary<string, List<Mappers.PredEdge>>();
        foreach (var p in exe.Paths)
        {
            if (!predecessors.TryGetValue(p.EndComponentRef, out var list))
            {
                list = new List<Mappers.PredEdge>();
                predecessors[p.EndComponentRef] = list;
            }
            string parentId = refToId.TryGetValue(p.StartComponentRef, out var pid)
                                 ? pid : YamlWriter.Id(p.StartComponentRef);
            string parentCls = refToClass.TryGetValue(p.StartComponentRef, out var pcl)
                                 ? pcl : "";
            list.Add(new Mappers.PredEdge
            {
                ParentId      = parentId,
                ParentPort    = p.StartPortName,
                ParentClassId = parentCls,
            });
        }

        foreach (var c in exe.Components)
        {
            predecessors.TryGetValue(c.RefId, out var preds);
            string? fromId = (preds != null && preds.Count > 0)
                                ? Mappers.PredEdge.From(preds[0]) : null;

            switch (c.ClassId)
            {
                /* Sources / sinks */
                case "Microsoft.OLEDBSource":
                    Mappers.OledbSource.Emit(w, pkg, c);
                    break;
                case "Microsoft.OLEDBDestination":
                    Mappers.OledbDestination.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.FlatFileSource":
                    Mappers.FlatFileSource.Emit(w, pkg, c);
                    break;
                case "Microsoft.FlatFileDestination":
                    Mappers.FlatFileDestination.Emit(w, pkg, c, fromId);
                    break;

                /* Transforms */
                case "Microsoft.ConditionalSplit":
                    Mappers.ConditionalSplit.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Aggregate":
                    Mappers.Aggregate.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Sort":
                    Mappers.Sort.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Lookup":
                    Mappers.Lookup.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.MergeJoin":
                    Mappers.MergeJoin.Emit(w, pkg, c, preds);
                    break;
                case "Microsoft.UnionAll":
                    Mappers.UnionAll.Emit(w, pkg, c, preds);
                    break;
                case "Microsoft.Multicast":
                    Mappers.Multicast.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.DerivedColumn":
                    Mappers.DerivedColumn.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.DataConvert":
                    Mappers.DataConvert.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Pivot":
                case "Microsoft.PivotTransform":
                    Mappers.Pivot.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.UnPivot":
                case "Microsoft.UnPivotTransform":
                    Mappers.Unpivot.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.ScriptComponentHost":
                case "Microsoft.ScriptComponent":
                    Mappers.ScriptComponent.Emit(w, pkg, c, fromId);
                    break;

                default:
                    w.Line($"- id: {YamlWriter.Id(c.Name)}");
                    w.Indent(2);
                    w.Comment($"TODO: component class '{c.ClassId}' not yet "
                            + "supported — manual migration required");
                    if (fromId != null) w.Line($"from: {fromId}");
                    w.Indent(-2);
                    break;
            }
        }
        w.Indent(-2);
        w.Indent(-2);
    }
}
